### ISSUE TITLE
push image to privete registry twice, but got different digest

### ISSUE THREAD

**Issue by kinzess** [docker/distribution#1771]
root@red-B85M-DS3H-A:~# docker run  -idt -p 5000:5000 registry:2
8bfb994048b6400d4fde1f20eb66bd6e121ce387a7f3481db4380bb4c75eae47
root@red-B85M-DS3H-A:~# docker push 10.202.165.145:5000/busybox
The push refers to a repository [10.202.165.145:5000/busybox]
5f70bf18a086: Pushed 
9508eff2c687: Pushed 
latest: digest: sha256:f0f4ab1d9a0a28145332c0f713a3dd64cc7a643b8883c1ee26b0e7a4cb66db39 size: 733
root@red-B85M-DS3H-A:~# docker push 10.202.165.145:5000/busybox
The push refers to a repository [10.202.165.145:5000/busybox]
5f70bf18a086: Layer already exists 
9508eff2c687: Layer already exists 
latest: digest: sha256:7638dc75fb6d456b00512a63073ab49e68f8033a8236061bf44bd4641cbd21a8 size: 711

I run a registry,then push image. 
I got one digest like above.
But when i push again immediately, got other digest.

**Comment by dmcgowan** [comment]
What is your version of docker and registry? Paste the output of `docker info` and `docker run registry:2 registry --version`.

We do not guarantee the result of 2 pushes will produce manifest digest. Although we have made efforts to make that digest stable. Since Docker 1.10 and Registry 2.3 the push digests have become very stable. In your case, it appears that no new layers were pushed and the tag has not changed so I do find it surprising and we can help you investigate.

**Comment by kinzess** [comment]
root@red-B85M-DS3H-A:~# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 188
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-8:5-1447690-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 12.48 GB
 Data Space Total: 107.4 GB
 Data Space Available: 33.18 GB
 Metadata Space Used: 17.02 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.13 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.18.0-031800-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.699 GiB
Name: red-B85M-DS3H-A
ID: QNXV:3A3S:34J3:NW6B:5ULI:YFLD:WT5P:ACE5:ASKY:YKV2:IS2X:XZ67
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support


root@red-B85M-DS3H-A:~# docker run registry:2 registry --version
/bin/registry github.com/docker/distribution v2.4.1

**Comment by RichardScothern** [comment]
@kinzess can you `curl` the manifests at those digests and paste them here?

**Comment by kinzess** [comment]
root@red-B85M-DS3H-A:~# curl -i 10.202.165.145:5000/v2/busybox/manifests/sha256:f0f4ab1d9a0a28145332c0f713a3dd64cc7a643b8883c1ee26b0e7a4cb66db39 
HTTP/1.1 200 OK
Content-Length: 733
Content-Type: application/vnd.docker.distribution.manifest.v2+json
Docker-Content-Digest: sha256:f0f4ab1d9a0a28145332c0f713a3dd64cc7a643b8883c1ee26b0e7a4cb66db39
Docker-Distribution-Api-Version: registry/2.0
Etag: "sha256:f0f4ab1d9a0a28145332c0f713a3dd64cc7a643b8883c1ee26b0e7a4cb66db39"
X-Content-Type-Options: nosniff
Date: Thu, 16 Jun 2016 07:06:26 GMT

{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 1374,
      "digest": "sha256:d9551b4026f0e2950ddb557cc640871710bf88476ca938b71499305647231b82"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 675865,
         "digest": "sha256:d7e8ec85c5abc60edf74bd4b8d68049350127e4102a084f22060f7321eac3586"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      }
   ]
}

other is:
root@red-B85M-DS3H-A:~# curl -i 10.202.165.145:5000/v2/busybox/manifests/sha256:7638dc75fb6d456b00512a63073ab49e68f8033a8236061bf44bd4641cbd21a8 
HTTP/1.1 200 OK
Content-Length: 711
Content-Type: application/vnd.docker.distribution.manifest.v2+json
Docker-Content-Digest: sha256:7638dc75fb6d456b00512a63073ab49e68f8033a8236061bf44bd4641cbd21a8
Docker-Distribution-Api-Version: registry/2.0
Etag: "sha256:7638dc75fb6d456b00512a63073ab49e68f8033a8236061bf44bd4641cbd21a8"
X-Content-Type-Options: nosniff
Date: Thu, 16 Jun 2016 07:07:16 GMT

{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/octet-stream",
      "size": 1374,
      "digest": "sha256:d9551b4026f0e2950ddb557cc640871710bf88476ca938b71499305647231b82"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 675865,
         "digest": "sha256:d7e8ec85c5abc60edf74bd4b8d68049350127e4102a084f22060f7321eac3586"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      }
   ]
}

**Comment by RichardScothern** [comment]
The mediatypes for the runtime config are different (`application/octet-stream` vs  `application/vnd.docker.container.image.v1+json`).  IIRC this has been fixed, but I'll double check.

**Comment by RichardScothern** [comment]
@kinzess this should be fixed in 1.11.2.  Could you retest with that version please?

**Comment by kinzess** [comment]
@RichardScothern i retest this, but not fix in 1.11.2

root@red-B85M-DS3H-A:~# docker info
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 189
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-8:5-1447690-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 12.69 GB
 Data Space Total: 107.4 GB
 Data Space Available: 32.94 GB
 Metadata Space Used: 17.6 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.13 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.18.0-031800-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.699 GiB
Name: red-B85M-DS3H-A
ID: QNXV:3A3S:34J3:NW6B:5ULI:YFLD:WT5P:ACE5:ASKY:YKV2:IS2X:XZ67
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

**Comment by recyard** [comment]
+1 not fixed. Docker 1.11.2, registry 2.4.1.

**Comment by recyard** [comment]
@RichardScothern, I'm using the latest 2.5.0-rc2 to verify since I see the fix is included, but it seems the issue still exists.

root@10.58.113.77:~# docker -v
Docker version 1.11.2, build b9f10c9
root@10.58.113.77:~# docker ps
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS                    NAMES
d3b2c0900f87        registry:2.5.0-rc.2   "/entrypoint.sh /etc/"   4 minutes ago       Up 4 minutes        0.0.0.0:5000->5000/tcp   drunk_albattani
root@10.58.113.77:~# **docker push 10.58.113.77:5000/base/registry:2.4.1**
The push refers to a repository [10.58.113.77:5000/base/registry]
ee8e809cfde5: Pushed
ba20d499f984: Pushed
705e35f12f24: Pushed
42755cf4ee95: Pushed
2.4.1: digest: **sha256:b66c4af9577744ae6d32e975808230e2ff558a5d50a7968d5102a900e147f3d5** size: 1158
root@10.58.113.77:~# **docker push 10.58.113.77:5000/base/registry:2.4.1**
The push refers to a repository [10.58.113.77:5000/base/registry]
ee8e809cfde5: Layer already exists
ba20d499f984: Layer already exists
705e35f12f24: Layer already exists
42755cf4ee95: Layer already exists
2.4.1: digest: **sha256:504b44c0ca43f9243ffa6feaf3934dd57895aece36b87bc25713588cdad3dd10** size: 1136

**Comment by RichardScothern** [comment]
The fix is for the client side code in the daemon - the code lives in this repository.

**Comment by recyard** [comment]
Thanks, confirmed fix using docker 1.12.0-rc4/registry 2.5.0-rc2.
